### ISSUE TITLE
Build image does not work

### ISSUE THREAD

**Issue by bnlcnd** [container-images/postfix#17]
there are many variables defined in the Dockerfile. the simple build command does not work at all.

```
# docker build -t postfix .
Sending build context to Docker daemon   362 kB
Error response from daemon: Syntax error - can't find = in "spec.expose". Must be of the form: name=value
```

(@TomasTomecek edited formatting)

**Comment by TomasTomecek** [comment]
Hi, the documentation and naming is wrong.

The issue you are experiencing is that we templated the Dockerfile so that we don't have to maintain multiple copies for different platforms. The tool we use for that is called [distgen](https://github.com/devexp-db/distgen).

@phracek would you be able to fix the documentation in readme and rename the Dockerfile to `Dockerfile.template`?

**Comment by TomasTomecek** [comment]
@phracek ping

**Comment by phracek** [comment]
yes, sure.
