### ISSUE TITLE
Postfix & Dovecot separation

### ISSUE THREAD

**Issue by LorbusChris** [container-images/postfix#3]
There seems to be a lot of overlap with the [dovecot module/container](https://github.com/container-images/dovecot). I think there shouldn't be that much duplication but instead two separate modules/containers that work together seamlessly.

Q: Is there an official stance on this by Fedora Modularity? (IMAP Module vs Postfix/Dovecot Modules)
+1 for clear separation

Q: Should Dovecot and Postfix then still communicate via unix-socket file (e.g. on a shared volume, if that is even possible) or else (e.g. ~~LDAP~~ LMTP(S) over inet socket)?
~~I'm +1 for default LMTPS(S)~~ 

I'd like to help with postfix, dovecot and also contribute to rspamd and nextcloud modules/containers development if I get around to that. I think a good first start could be to clean up this repo and make it adhere to the templating proposed in container-image-template. Please do point me to the right direction. 
Cheers, Chris

Edit: It should have been LMTP(S) for postfix->dovecot, not LDAP - my bad, I got confused :smile: I picked up some chatter that FreeIPA was going to be modularized for f27, at which point I shall have another look at LDAP.

**Comment by TomasTomecek** [comment]
Hi Chris, thanks for taking time to look into these modules and containers!

Unfortunately, we didn't have time to finish the work on postfix and dovecot for boltron so that's why it's kind of messy.

> Q: Is there an official stance on this by Fedora Modularity? (IMAP Module vs Postfix/Dovecot Modules)

I agree that having those containers and modules separated would be ideal.

> Q: Should Dovecot and Postfix then still communicate via unix-socket file (e.g. on a shared volume, if that is even possible) or else (e.g. LDAP(S) over inet socket)?

Unfortunately I can't answer this question personally, since I wasn't the engineer involved in these modules (@phracek was). The solution you described, mount shared volume inside both containers and let them communicate via unix socket, sounds doable from my point of view.


I just created tasks to review these modules and containers and added the task to backlog. Hopefully we'll have time to look into this next sprint.

For next steps, let's wait for @phracek to respond and then we can figure out what to do.

**Comment by phracek** [comment]
Yesterday, I have read it and it make sense to me. I will work on it in my spare time. I am a bit busy with other tasks.
@LorbusChris I will create a PR and let me know whether it works for you. And thanks for the important feedback.

**Comment by phracek** [comment]
@LorbusChris Can you please help us with this issue?

**Comment by LorbusChris** [comment]
@TomasTomecek @phracek Thanks for the quick responses! Will test tonight (UTC+1) :)

**Comment by LorbusChris** [comment]
I've come up with a few more Questions:

What parts of the Postfix config, if any, have to change when deploying in conjunction with Dovecot container?
Can all Dovecot related scripts be removed from this repo?
Are multiple Dockerfiles and Openshift Templates necessary?

**Comment by phracek** [comment]
@LorbusChris See PR #11 . All those files will be removed soon, once PR is merged.
